server:
  port: 8080

spring:
  datasource:
    password: Nico@tut2016
    url: jdbc:mysql://localhost:3306/contractsdb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  application:
    name: CONTRACT-REPAYMENT-SERVICE
  config:
    import: configserver:http://localhost:9296
  cloud:
    compatibility-verifier:
      enabled: false

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
